// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection

[<assembly: AssemblyTitleAttribute("feltlion")>]
[<assembly: AssemblyProductAttribute("feltlion")>]
[<assembly: AssemblyDescriptionAttribute("Slack integration written with F#")>]
[<assembly: AssemblyVersionAttribute("1.0")>]
[<assembly: AssemblyFileVersionAttribute("1.0")>]
[<assembly: AssemblyConfigurationAttribute("Release")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyTitle = "feltlion"
    let [<Literal>] AssemblyProduct = "feltlion"
    let [<Literal>] AssemblyDescription = "Slack integration written with F#"
    let [<Literal>] AssemblyVersion = "1.0"
    let [<Literal>] AssemblyFileVersion = "1.0"
    let [<Literal>] AssemblyConfiguration = "Release"
